language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure:
    app: lit-atoll-80185
  on:
    repo: Level-turing-team/level_backend
    branch: main
  skip_cleanup: 'true'
  run: rails db:{migrate,seed}
