Profile.destroy_all
Post.destroy_all
Circle.destroy_all
Tag.destroy_all
ProfileTag.destroy_all
Gallery.destroy_all
Photo.destroy_all

@profile_1 = Profile.create(username: 'the painter man', user_id: 1, zipcode: '80301', profile_picture: 'http://www.google.com')
@profile_2 = Profile.create(username: 'korn', user_id: 2, zipcode: '80305', profile_picture: 'http://www.google.com')
@profile_3 = Profile.create(username: 'slipknot', user_id: 3, zipcode: '80304', profile_picture: 'http://www.google.com')
@profile_4 = Profile.create(username: 'photos by jim', user_id: 4, zipcode: '80303', profile_picture: 'http://www.google.com')
@profile_5 = Profile.create(username: 'arteest', user_id: 5, zipcode: '80544', profile_picture: 'http://www.google.com')

@tag_1 = Tag.create(name: 'Painter')
@tag_2 = Tag.create(name: 'Musician')
@tag_3 = Tag.create(name: 'Sculpter')
@tag_4 = Tag.create(name: 'Photographer')
@tag_5 = Tag.create(name: 'Drummer')

ProfileTag.create(user_id: @profile_1.user_id, tag_id: @tag_1.id)
ProfileTag.create(user_id: @profile_1.user_id, tag_id: @tag_3.id)
ProfileTag.create(user_id: @profile_2.user_id, tag_id: @tag_4.id)
ProfileTag.create(user_id: @profile_2.user_id, tag_id: @tag_5.id)
ProfileTag.create(user_id: @profile_3.user_id, tag_id: @tag_1.id)
ProfileTag.create(user_id: @profile_3.user_id, tag_id: @tag_2.id)
ProfileTag.create(user_id: @profile_4.user_id, tag_id: @tag_1.id)
ProfileTag.create(user_id: @profile_5.user_id, tag_id: @tag_2.id)

Circle.create(user_id: @profile_1.user_id, following_id: @profile_2.user_id)
Circle.create(user_id: @profile_1.user_id, following_id: @profile_3.user_id)
Circle.create(user_id: @profile_1.user_id, following_id: @profile_4.user_id)
Circle.create(user_id: @profile_1.user_id, following_id: @profile_5.user_id)
Circle.create(user_id: @profile_2.user_id, following_id: @profile_1.user_id)
Circle.create(user_id: @profile_2.user_id, following_id: @profile_3.user_id)
Circle.create(user_id: @profile_2.user_id, following_id: @profile_4.user_id)
Circle.create(user_id: @profile_2.user_id, following_id: @profile_5.user_id)
Circle.create(user_id: @profile_3.user_id, following_id: @profile_1.user_id)
Circle.create(user_id: @profile_3.user_id, following_id: @profile_2.user_id)
Circle.create(user_id: @profile_3.user_id, following_id: @profile_4.user_id)
Circle.create(user_id: @profile_3.user_id, following_id: @profile_5.user_id)
Circle.create(user_id: @profile_3.user_id, following_id: @profile_5.user_id)
Circle.create(user_id: @profile_4.user_id, following_id: @profile_1.user_id)
Circle.create(user_id: @profile_4.user_id, following_id: @profile_3.user_id)
Circle.create(user_id: @profile_4.user_id, following_id: @profile_5.user_id)


@post1 = Post.create(user_id: @profile1.user_id, content: "hey did you see that lil nas X video?" , link:"photoURL.com", created_at: 2021-02-27)
@post2 = Post.create(user_id: @profile1.user_id, content: "hey did you see that create meme?" , link:"photoURL.com", created_at: 2021-01-27)
@post3 = Post.create(user_id: @profile1.user_id, content: "hey did you see that riot footage?", created_at: 2021-02-15)
@post4 = Post.create(user_id: @profile2.user_id, content: "hey did you see that headline?" , link:"photoURL.com", created_at: 2021-03-27)
@post5 = Post.create(user_id: @profile2.user_id, content: "hey checkout my create shoes?" , link:"photoURL.com", created_at: 2021-03-01)
@post6 = Post.create(user_id: @profile3.user_id, content: "hey did you see software update?" , link:"photoURL.com", created_at: 2021-03-21)
@post7 = Post.create(user_id: @profile3.user_id, content: "hey did you see your mom called?", created_at: 2021-03-25)
@post8 = Post.create(user_id: @profile4.user_id, content: "hey did you see that we're not friends on FB anymore?" , link:"photoURL.com", created_at: 2021-03-23)
@post9 = Post.create(user_id: @profile4.user_id, content: "hey did you see hear about that create app called 'level'?" , link:"photoURL.com", created_at: 2021-03-13)
@post10 = Post.create(user_id: @profile5.user_id, content: "hey i just got hired at a sick new comapny", created_at: 2021-04-13)

@gallery_1 = Gallery.create(user_id: @profile_1.user_id, name: "photos from cali", photo_url: 'http://www.google.com')
@gallery_2 = Gallery.create(user_id: @profile_2.user_id, name: "sweet tatoos", photo_url: 'http://www.google.com')
@gallery_3 = Gallery.create(user_id: @profile_3.user_id, name: "my grandmas birthday", photo_url: 'http://www.google.com')
@gallery_4 = Gallery.create(user_id: @profile_4.user_id, name: "b&w realism", photo_url: 'http://www.google.com')
@gallery_5 = Gallery.create(user_id: @profile_5.user_id, name: "water colors", photo_url: 'http://www.google.com')
@gallery_6 = Gallery.create(user_id: @profile_2.user_id, name: "set from the theatre", photo_url: 'http://www.google.com')
@gallery_7 = Gallery.create(user_id: @profile_3.user_id, name: "level is super fun", photo_url: 'http://www.google.com')
@gallery_8 = Gallery.create(user_id: @profile_5.user_id, name: "joe's cat pics", photo_url: 'http://www.google.com')

@photo_1 = Photo.create(gallery_id: @gallery_1.id, description: 'pic 1', url: 'http:www.google.com')
@photo_2 = Photo.create(gallery_id: @gallery_1.id, description: 'pic 1', url: 'http:www.google.com')
@photo_3 = Photo.create(gallery_id: @gallery_1.id, description: 'pic 1', url: 'http:www.google.com')
@photo_4 = Photo.create(gallery_id: @gallery_2.id, description: 'pic 1', url: 'http:www.google.com')
@photo_5 = Photo.create(gallery_id: @gallery_2.id, description: 'pic 1', url: 'http:www.google.com')
@photo_6 = Photo.create(gallery_id: @gallery_3.id, description: 'pic 1', url: 'http:www.google.com')
@photo_7 = Photo.create(gallery_id: @gallery_3.id, description: 'pic 1', url: 'http:www.google.com')
@photo_8 = Photo.create(gallery_id: @gallery_4.id, description: 'pic 1', url: 'http:www.google.com')
@photo_9 = Photo.create(gallery_id: @gallery_4.id, description: 'pic 1', url: 'http:www.google.com')
@photo_10 = Photo.create(gallery_id: @gallery_5.id, description: 'pic 1', url: 'http:www.google.com')
@photo_11 = Photo.create(gallery_id: @gallery_5.id, description: 'pic 1', url: 'http:www.google.com')
@photo_12 = Photo.create(gallery_id: @gallery_5.id, description: 'pic 1', url: 'http:www.google.com')
@photo_13 = Photo.create(gallery_id: @gallery_6.id, description: 'pic 1', url: 'http:www.google.com')
@photo_14 = Photo.create(gallery_id: @gallery_6.id, description: 'pic 1', url: 'http:www.google.com')
@photo_15 = Photo.create(gallery_id: @gallery_6.id, description: 'pic 1', url: 'http:www.google.com')
@photo_16 = Photo.create(gallery_id: @gallery_7.id, description: 'pic 1', url: 'http:www.google.com')
@photo_17 = Photo.create(gallery_id: @gallery_7.id, description: 'pic 1', url: 'http:www.google.com')
@photo_18 = Photo.create(gallery_id: @gallery_7.id, description: 'pic 1', url: 'http:www.google.com')
@photo_19 = Photo.create(gallery_id: @gallery_8.id, description: 'pic 1', url: 'http:www.google.com')
@photo_20 = Photo.create(gallery_id: @gallery_8.id, description: 'pic 1', url: 'http:www.google.com')
@photo_21 = Photo.create(gallery_id: @gallery_8.id, description: 'pic 1', url: 'http:www.google.com')
@photo_22 = Photo.create(gallery_id: @gallery_8.id, description: 'pic 1', url: 'http:www.google.com')

